"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { DynamicIcon, type IconName } from "lucide-react/dynamic";
import Link from "next/link";

type FAQItem = {
  id: string;
  icon: IconName;
  question: string;
  answer: string;
};

export default function FAQsThree() {
  const faqItems: FAQItem[] = [
    {
      id: "item-1",
      icon: "clock",
      question: "How long does SEO take?",
      answer: "Typically 3–6 months depending on competition and industry.",
    },
    {
      id: "item-2",
      icon: "credit-card",
      question: "Do you guarantee rankings?",
      answer:
        "No ethical agency can guarantee #1 rankings — but we guarantee consistent growth.",
    },
    {
      id: "item-3",
      icon: "globe",
      question: "What is the difference between GEO & AEO?",
      answer:
        "GEO improves visibility in location-based searches & Google Maps. AEO makes your brand appear in answers generated by AI engines.",
    },
    {
      id: "item-4",
      icon: "truck",
      question: "Do you offer localized support?",
      answer:
        "Our support team can assist clients via email, chat, and phone during standard business hours for each respective region.",
    },
    {
      id: "item-5",
      icon: "package",
      question: "What is included in the free SEO audit?",
      answer:
        "Technical analysis, keyword opportunities, competitor insights, and traffic growth plan.",
    },
  ];

  return (
    <section className="bg-muted dark:bg-background py-20" id="faqs">
      <div className="mx-auto max-w-5xl px-4 md:px-6">
        <div className="flex flex-col gap-10 md:flex-row md:gap-16">
          <div className="md:w-1/3">
            <div className="sticky top-20">
              <h2 className="mt-4 text-3xl font-bold">
                Frequently Asked Questions
              </h2>
              <p className="text-muted-foreground mt-4">
                Can't find what you're looking for? Contact our{" "}
                <Link
                  href="#"
                  className="text-primary font-medium hover:underline"
                >
                  customer support team
                </Link>
              </p>
            </div>
          </div>
          <div className="md:w-2/3">
            <Accordion type="single" collapsible className="w-full space-y-2">
              {faqItems.map((item) => (
                <AccordionItem
                  key={item.id}
                  value={item.id}
                  className="bg-background shadow-xs rounded-lg border px-4 last:border-b"
                >
                  <AccordionTrigger className="cursor-pointer items-center py-5 hover:no-underline">
                    <div className="flex items-center gap-3">
                      <div className="flex size-6">
                        <DynamicIcon
                          name={item.icon}
                          className="m-auto size-4"
                        />
                      </div>
                      <span className="text-base">{item.question}</span>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pb-5">
                    <div className="px-9">
                      <p className="text-base">{item.answer}</p>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  );
}
